"""empty message

Revision ID: 2f9b2fec463a
Revises: 
Create Date: 2025-04-29 02:00:34.701679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f9b2fec463a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blacklist_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blacklist_tokens_jti'), ['jti'], unique=False)

    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=True),
    sa.Column('razon_social', sa.String(length=120), nullable=True),
    sa.Column('nombrerp', sa.String(length=120), nullable=True),
    sa.Column('apellidorp', sa.String(length=120), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('ubicacion', sa.String(length=120), nullable=True),
    sa.Column('sitio_web', sa.String(length=220), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=120), nullable=True),
    sa.Column('rfc', sa.String(length=13), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresa_email'), ['email'], unique=True)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('nombre', sa.String(length=120), nullable=True),
    sa.Column('apellido', sa.String(length=120), nullable=True),
    sa.Column('numero', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('cv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portafolio', sa.String(length=220), nullable=True),
    sa.Column('experiencia', sa.String(length=220), nullable=True),
    sa.Column('cursos', sa.String(length=220), nullable=True),
    sa.Column('capacitaciones', sa.String(length=220), nullable=True),
    sa.Column('estudios', sa.String(length=220), nullable=True),
    sa.Column('idiomas', sa.String(length=220), nullable=True),
    sa.Column('tecnologia', sa.String(length=220), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_nacimiento', sa.String(length=120), nullable=True),
    sa.Column('lugar', sa.String(length=220), nullable=True),
    sa.Column('acerca', sa.String(length=220), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trabajos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('modalidad', sa.String(length=120), nullable=True),
    sa.Column('descripcion', sa.String(length=120), nullable=True),
    sa.Column('nombre_puesto', sa.String(length=120), nullable=True),
    sa.Column('remuneracion', sa.Integer(), nullable=True),
    sa.Column('condiciones', sa.String(length=250), nullable=True),
    sa.Column('responsabilidades', sa.String(length=250), nullable=True),
    sa.Column('requerimientos', sa.String(length=250), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_trabajo', sa.Integer(), nullable=False),
    sa.Column('id_trabajador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_trabajador'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_trabajo'], ['trabajos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postulacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_trabajo', sa.Integer(), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('id_trabajador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['id_trabajador'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_trabajo'], ['trabajos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postulacion')
    op.drop_table('favoritos')
    op.drop_table('trabajos')
    op.drop_table('perfiles')
    op.drop_table('cv')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresa_email'))

    op.drop_table('empresa')
    with op.batch_alter_table('blacklist_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blacklist_tokens_jti'))

    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
