"""empty message

Revision ID: 53efd8b854af
Revises: 75dcec90d04c
Create Date: 2025-04-18 04:46:36.428320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53efd8b854af'
down_revision = '75dcec90d04c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trabajadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.String(length=20), nullable=False),
    sa.Column('nacionalidad', sa.String(length=50), nullable=False),
    sa.Column('ubicacion', sa.String(length=120), nullable=False),
    sa.Column('resumen_profesional', sa.String(length=1000), nullable=False),
    sa.Column('habilidades', sa.String(length=1000), nullable=False),
    sa.Column('idiomas', sa.String(length=250), nullable=False),
    sa.Column('nivel_academico', sa.String(length=100), nullable=False),
    sa.Column('linkedin', sa.String(length=255), nullable=False),
    sa.Column('github', sa.String(length=255), nullable=False),
    sa.Column('portafolio', sa.String(length=255), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('aptitudes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cursos_capacitacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('institucion', sa.String(length=150), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('educacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=True),
    sa.Column('institucion', sa.String(length=150), nullable=True),
    sa.Column('nivel', sa.String(length=100), nullable=True),
    sa.Column('titulo', sa.String(length=150), nullable=True),
    sa.Column('inicio', sa.String(length=20), nullable=True),
    sa.Column('fin', sa.String(length=20), nullable=True),
    sa.Column('estatus', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiencia_laboral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=True),
    sa.Column('empresa', sa.String(length=100), nullable=True),
    sa.Column('puesto', sa.String(length=100), nullable=True),
    sa.Column('modalidad', sa.String(length=50), nullable=True),
    sa.Column('inicio', sa.String(length=20), nullable=True),
    sa.Column('fin', sa.String(length=20), nullable=True),
    sa.Column('ubicacion', sa.String(length=120), nullable=True),
    sa.Column('responsabilidades', sa.Text(), nullable=True),
    sa.Column('logros', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intereses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intereses')
    op.drop_table('experiencia_laboral')
    op.drop_table('educacion')
    op.drop_table('cursos_capacitacion')
    op.drop_table('aptitudes')
    op.drop_table('trabajadores')
    # ### end Alembic commands ###
