"""empty message

Revision ID: 75dcec90d04c
Revises: 0763d677d453
Create Date: 2025-04-17 17:29:39.287224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75dcec90d04c'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trabajos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modalidad', sa.String(length=120), nullable=False),
    sa.Column('nombre_puesto', sa.String(length=120), nullable=False),
    sa.Column('remuneracion', sa.Integer(), nullable=True),
    sa.Column('condiciones', sa.String(length=250), nullable=False),
    sa.Column('responsabilidades', sa.String(length=250), nullable=False),
    sa.Column('requerimientos', sa.String(length=250), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trabajos')
    # ### end Alembic commands ###
