"""empty message

Revision ID: 958f5041f0c8
Revises: 0763d677d453
Create Date: 2025-04-17 17:38:35.892037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958f5041f0c8'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('black_list_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('black_list_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_black_list_token_jti'), ['jti'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('apellido', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('numero', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('acerca', sa.String(length=220), nullable=False))
        batch_op.add_column(sa.Column('portafolio', sa.String(length=220), nullable=False))
        batch_op.add_column(sa.Column('experiencia', sa.String(length=220), nullable=False))
        batch_op.add_column(sa.Column('cursos', sa.String(length=220), nullable=False))
        batch_op.add_column(sa.Column('capacitaciones', sa.String(length=220), nullable=False))
        batch_op.add_column(sa.Column('estudios', sa.String(length=220), nullable=False))
        batch_op.add_column(sa.Column('idiomas', sa.String(length=220), nullable=False))
        batch_op.add_column(sa.Column('tecnologia', sa.String(length=220), nullable=False))
        batch_op.add_column(sa.Column('lugar', sa.String(length=220), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.create_unique_constraint(None, ['numero'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('lugar')
        batch_op.drop_column('tecnologia')
        batch_op.drop_column('idiomas')
        batch_op.drop_column('estudios')
        batch_op.drop_column('capacitaciones')
        batch_op.drop_column('cursos')
        batch_op.drop_column('experiencia')
        batch_op.drop_column('portafolio')
        batch_op.drop_column('acerca')
        batch_op.drop_column('numero')
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    with op.batch_alter_table('black_list_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_black_list_token_jti'))

    op.drop_table('black_list_token')
    # ### end Alembic commands ###
